import { test } from "node:test";
import assert from "node:assert/strict";
import type { DiffFile } from "../src/diff-extract.ts";
import {
  GUARDRAIL_PATH_RULES,
  MECHANICAL_PATH_RULES,
  classifyFile,
  type ClassifyConfig,
  type PathRule,
} from "../src/classify.ts";

function file(path: string, overrides: Partial<DiffFile> = {}): DiffFile {
  return {
    path,
    status: "modified",
    diff: "",
    insertions: 0,
    deletions: 0,
    oversized: false,
    ...overrides,
  };
}

/** A patch with the `diff --git`/`index`/`---`/`+++` header a real one carries. */
function patch(path: string, body: string): string {
  return [
    `diff --git a/${path} b/${path}`,
    "index 1111111111111111111111111111111111111111..2222222222222222222222222222222222222222 100644",
    `--- a/${path}`,
    `+++ b/${path}`,
    body,
  ].join("\n");
}

function globs(overrides: Partial<ClassifyConfig> = {}): ClassifyConfig {
  return { mechanical: [], guardrail: [], ...overrides };
}

test("a rename git scored 100% identical is mechanical: nothing in it is a decision", () => {
  const renamed = file("app/models/orders/order.rb", {
    status: "renamed",
    previousPath: "app/models/order.rb",
    similarity: 100,
    diff: [
      "diff --git a/app/models/order.rb b/app/models/orders/order.rb",
      "similarity index 100%",
      "rename from app/models/order.rb",
      "rename to app/models/orders/order.rb",
    ].join("\n"),
  });

  assert.deepEqual(classifyFile(renamed), { mechanical: true, guardrail: false });
});

test("a rename that also changed lines is not mechanical — the change is the point", () => {
  const renamed = file("app/models/orders/order.rb", {
    status: "renamed",
    previousPath: "app/models/order.rb",
    similarity: 96,
    insertions: 4,
    deletions: 2,
    diff: [
      "diff --git a/app/models/order.rb b/app/models/orders/order.rb",
      "similarity index 96%",
      "rename from app/models/order.rb",
      "rename to app/models/orders/order.rb",
      "--- a/app/models/order.rb",
      "+++ b/app/models/orders/order.rb",
      "@@ -1,5 +1,7 @@",
      "-class Order",
      "+module Orders",
      "+  class Order",
    ].join("\n"),
  });

  assert.equal(classifyFile(renamed).mechanical, false);
});

test("a generated Go file is mechanical: its own banner says so", () => {
  const generated = file("internal/api/types.pb.go", {
    insertions: 1,
    deletions: 1,
    diff: patch(
      "internal/api/types.pb.go",
      [
        "@@ -1,7 +1,7 @@",
        " // Code generated by protoc-gen-go. DO NOT EDIT.",
        " // versions:",
        "-//   protoc-gen-go v1.31.0",
        "+//   protoc-gen-go v1.32.0",
        " ",
        " package api",
      ].join("\n"),
    ),
  });

  assert.deepEqual(classifyFile(generated), { mechanical: true, guardrail: false });
});

test("`@generated` in an added line marks a newly generated file", () => {
  const added = file("web/src/schema.ts", {
    status: "added",
    insertions: 3,
    diff: patch(
      "web/src/schema.ts",
      [
        "@@ -0,0 +1,3 @@",
        "+/** @generated by graphql-codegen */",
        "+",
        "+export type Query = {};",
      ].join("\n"),
    ),
  });

  assert.equal(classifyFile(added).mechanical, true);
});

test("a patch that removes the banner is a generated file becoming a hand-written one", () => {
  const adopted = file("internal/api/types.go", {
    insertions: 1,
    deletions: 1,
    diff: patch(
      "internal/api/types.go",
      [
        "@@ -1,4 +1,4 @@",
        "-// Code generated by protoc-gen-go. DO NOT EDIT.",
        "+// Hand-maintained since the generator was dropped.",
        " ",
        " package api",
      ].join("\n"),
    ),
  });

  assert.equal(classifyFile(adopted).mechanical, false);
});

test("a marker far down the patch decides nothing — it is as likely a printed string", () => {
  const deep = file("internal/warn/banner.go", {
    insertions: 1,
    diff: patch(
      "internal/warn/banner.go",
      [
        "@@ -40,6 +40,7 @@ func Warn() {",
        ...Array.from({ length: 24 }, (_, index) => ` \tstep(${index})`),
        '+\tfmt.Println("DO NOT EDIT")',
      ].join("\n"),
    ),
  });

  assert.equal(classifyFile(deep).mechanical, false);
});

test("a whitespace-only reformat is mechanical: every line came back with its content", () => {
  const reformatted = file("orders/service.py", {
    insertions: 3,
    deletions: 3,
    diff: patch(
      "orders/service.py",
      [
        "@@ -1,6 +1,6 @@",
        " def total(order):",
        "-  subtotal = sum(line.amount for line in order.lines)",
        "-  tax = subtotal * TAX_RATE",
        "-  return subtotal + tax",
        "+    subtotal = sum(line.amount for line in order.lines)",
        "+    tax = subtotal * TAX_RATE",
        "+    return subtotal + tax",
      ].join("\n"),
    ),
  });

  assert.deepEqual(classifyFile(reformatted), { mechanical: true, guardrail: false });
});

test("a reformat carrying one real edit is not whitespace-only", () => {
  const edited = file("orders/service.py", {
    insertions: 2,
    deletions: 2,
    diff: patch(
      "orders/service.py",
      [
        "@@ -1,4 +1,4 @@",
        " def total(order):",
        "-  subtotal = sum(line.amount for line in order.lines)",
        "-  return subtotal * TAX_RATE",
        "+    subtotal = sum(line.amount for line in order.lines)",
        "+    return subtotal * VAT_RATE",
      ].join("\n"),
    ),
  });

  assert.equal(classifyFile(edited).mechanical, false);
});

test("a duplicated line is a change, however identical its two copies look", () => {
  const duplicated = file("orders/service.py", {
    insertions: 2,
    deletions: 1,
    diff: patch(
      "orders/service.py",
      ["@@ -1,3 +1,4 @@", "-  log(order)", "+  log(order)", "+  log(order)"].join("\n"),
    ),
  });

  assert.equal(classifyFile(duplicated).mechanical, false);
});

test("a Terraform change is guardrail: infrastructure is never bulk", () => {
  const infra = file("infra/main.tf", {
    insertions: 2,
    deletions: 1,
    diff: patch(
      "infra/main.tf",
      [
        '@@ -12,3 +12,4 @@ resource "aws_s3_bucket" "artifacts" {',
        '-  acl = "private"',
        '+  acl = "public-read"',
        "+  force_destroy = true",
      ].join("\n"),
    ),
  });

  assert.deepEqual(classifyFile(infra), { mechanical: false, guardrail: true });
});

test("a lockfile is guardrail and never mechanical, however it was generated", () => {
  const lock = file("Gemfile.lock", {
    insertions: 2,
    deletions: 2,
    diff: patch(
      "Gemfile.lock",
      [
        "@@ -102,8 +102,8 @@ GEM",
        "-    rack (2.2.6.4)",
        "-    rails (7.0.4)",
        "+    rack (3.0.8)",
        "+    rails (7.1.2)",
      ].join("\n"),
    ),
  });

  assert.deepEqual(classifyFile(lock), { mechanical: false, guardrail: true });
});

/**
 * The rule the whole module turns on. Both files would be mechanical on their
 * diff alone — one is a rename git scored 100%, the other pure re-indentation.
 */
test("guardrail wins over every mechanical rule", () => {
  const movedWorkflow = file(".github/workflows/release.yml", {
    status: "renamed",
    previousPath: ".github/workflows/publish.yml",
    similarity: 100,
    diff: [
      "diff --git a/.github/workflows/publish.yml b/.github/workflows/release.yml",
      "similarity index 100%",
    ].join("\n"),
  });
  const reindentedScript = file("scripts/deploy.sh", {
    insertions: 1,
    deletions: 1,
    diff: patch(
      "scripts/deploy.sh",
      ["@@ -3,3 +3,3 @@", "-  rsync -a build/ $TARGET", "+    rsync -a build/ $TARGET"].join("\n"),
    ),
  });

  assert.deepEqual(classifyFile(movedWorkflow), { mechanical: false, guardrail: true });
  assert.deepEqual(classifyFile(reindentedScript), { mechanical: false, guardrail: true });
});

test("a file leaving a guardrail directory is still a guardrail change on its way out", () => {
  const moved = file("scripts/ci.yml", {
    status: "renamed",
    previousPath: ".github/workflows/ci.yml",
    similarity: 98,
    insertions: 1,
    deletions: 1,
  });

  assert.equal(classifyFile(moved).guardrail, true);
});

test("documentation is mechanical on its extension alone", () => {
  const doc = file("docs/setup.md", { insertions: 12, deletions: 4 });

  assert.deepEqual(classifyFile(doc), { mechanical: true, guardrail: false });
});

test("a file no rule claims carries neither mark", () => {
  const source = file("app/controllers/orders_controller.rb", {
    insertions: 30,
    deletions: 8,
    diff: patch(
      "app/controllers/orders_controller.rb",
      ["@@ -1,3 +1,3 @@", "-  def show", "+  def show_with_refunds"].join("\n"),
    ),
  });

  assert.deepEqual(classifyFile(source), { mechanical: false, guardrail: false });
});

test("user globs mark files the defaults never could", () => {
  const configured = globs({ mechanical: ["docs/api/**"], guardrail: ["app/payments/**"] });

  assert.equal(classifyFile(file("docs/api/orders.json"), configured).mechanical, true);
  assert.deepEqual(classifyFile(file("app/payments/charge.rb"), configured), {
    mechanical: false,
    guardrail: true,
  });
});

test("user globs add to the defaults, they do not replace them", () => {
  const configured = globs({ mechanical: ["docs/api/**"], guardrail: ["app/payments/**"] });

  assert.equal(classifyFile(file("install.sh"), configured).guardrail, true);
  assert.equal(classifyFile(file("README.md"), configured).mechanical, true);
});

test("a user mechanical glob cannot downgrade a guardrail file either", () => {
  const configured = globs({ mechanical: ["config/**"] });

  assert.deepEqual(classifyFile(file("config/Dockerfile"), configured), {
    mechanical: false,
    guardrail: true,
  });
});

test("`*` stops at a separator, `**` crosses it, and the rest is literal", () => {
  const star = globs({ mechanical: ["docs/*.json"] });
  const globstar = globs({ mechanical: ["docs/**"] });
  const literal = globs({ mechanical: ["db/schema.rb"] });

  assert.equal(classifyFile(file("docs/orders.json"), star).mechanical, true);
  assert.equal(classifyFile(file("docs/api/orders.json"), star).mechanical, false);
  assert.equal(classifyFile(file("docs/api/orders.json"), globstar).mechanical, true);
  assert.equal(classifyFile(file("db/schema.rb"), literal).mechanical, true);
  assert.equal(classifyFile(file("app/db/schema.rb"), literal).mechanical, false);
});

/** A `**` between two segments has to swallow its own separator, or `docs/x.md` escapes it. */
test("a `**` in the middle of a glob matches no directory at all", () => {
  const nested = globs({ guardrail: ["app/**/secrets.rb"] });

  assert.equal(classifyFile(file("app/secrets.rb"), nested).guardrail, true);
  assert.equal(classifyFile(file("app/models/admin/secrets.rb"), nested).guardrail, true);
  assert.equal(classifyFile(file("app/models/admin/keys.rb"), nested).guardrail, false);
});

test("a glob's regex characters are literal, so a `.` is a dot and nothing else", () => {
  const configured = globs({ mechanical: ["CHANGELOG.md"] });

  assert.equal(classifyFile(file("CHANGELOGxmd"), configured).mechanical, false);
});

/** Mirrors `TEST_PATH_CONVENTIONS`: a rule that stopped claiming its own examples fails here. */
function claims(rules: readonly PathRule[], path: string): PathRule[] {
  return rules.filter((rule) => rule.pattern.test(path));
}

for (const [table, rules] of [
  ["guardrail", GUARDRAIL_PATH_RULES],
  ["mechanical", MECHANICAL_PATH_RULES],
] as const) {
  test(`every ${table} rule claims its own examples`, () => {
    for (const rule of rules) {
      for (const example of rule.examples) {
        assert.ok(claims(rules, example).includes(rule), `${rule.name} lost ${example}`);
      }
    }
  });

  test(`no ${table} rule claims a counterexample of any rule`, () => {
    for (const rule of rules) {
      for (const counterexample of rule.counterexamples) {
        const claimants = claims(rules, counterexample).map((claimant) => claimant.name);
        assert.deepEqual(claimants, [], `${counterexample} was claimed by ${claimants.join(", ")}`);
      }
    }
  });

  test(`every ${table} rule is the sole claimant of at least one example`, () => {
    for (const rule of rules) {
      const sole = rule.examples.filter((example) => claims(rules, example).length === 1);
      assert.ok(sole.length > 0, `${rule.name} claims nothing another rule does not`);
    }
  });
}

/** The contract in the module comment, checked rather than promised. */
test("no default rule names a path out of this repository", () => {
  for (const rule of [...GUARDRAIL_PATH_RULES, ...MECHANICAL_PATH_RULES]) {
    assert.doesNotMatch(rule.pattern.source, /src\\\/(browser|llm|ledger|rounds|commands|server)/);
  }
});
